// Generated by CoffeeScript 1.7.1
var Clock;

Clock = (function() {
  function Clock() {
    this._last = 0;
    this.time = Number.MIN_VALUE;
    this.timeScale = 100;
    this.max_dt = 1 / 60;
    this.callbacks = [];
    this.dt = this.max_dt;
  }

  Clock.prototype.register = function(cb, context) {
    this.callbacks.push(cb.bind(context));
    return this;
  };

  Clock.prototype.delta = function() {
    return this.time - this._last;
  };

  Clock.prototype.tick = function() {
    var cb, _i, _len, _ref;
    this.dt = this.timeScale * Math.min(Date.now() - this._last, this.max_dt);
    this._last = this.time;
    this.time += this.dt;
    _ref = this.callbacks;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      cb = _ref[_i];
      cb();
    }
    return this;
  };

  return Clock;

})();
