// Generated by CoffeeScript 1.7.1
var StateMachine,
  __slice = [].slice;

StateMachine = (function() {
  StateMachine.prototype.currentState = 0;

  StateMachine.prototype.states = [];

  function StateMachine(states) {
    states.forEach((function(_this) {
      return function(s, i) {
        return _this.states[s] = Math.pow(2, i);
      };
    })(this));
  }

  StateMachine.prototype.isEnabled = function() {
    var state;
    state = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return (state.reduce((function(s1, s2) {
      return s1 & s2;
    }), this.state)) !== 0;
  };

  StateMachine.prototype.enable = function(state) {
    this.state |= this.states[state];
    return this;
  };

  StateMachine.prototype.disable = function(state) {
    this.state &= ~this.states[state];
    return this;
  };

  StateMachine.prototype.toggle = function(state) {
    this.state ^= this.states[state];
    return this;
  };

  return StateMachine;

})();
